/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "stm32f4xx.h"
#include "system_stm32f4xx.h"

#include "led.h"
#include "switch_intr.h"


#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{

	uint8_t switch_prssed =0;
	SystemInit();
	SwitchInit();
	LedInit(LED_ORANGE_PIN);
	LedInit(LED_RED_PIN);
	LedInit(LED_BLUE_PIN);



	while(1){

		// when switched is pressed then orange led is blink

		while(SwitchExtiFlag==0)
			;

		// turn off all led
		LedOff(LED_ORANGE_PIN);
		LedOff(LED_RED_PIN);
		LedOff(LED_BLUE_PIN);

		switch(switch_prssed)
		{
		case 0: // Blink the orange  led when switch is pressed
			LedBlink(LED_ORANGE_PIN,250);
			break;

		case 1:// Blink the RED  led when switch is pressed
			LedBlink(LED_RED_PIN,250);
			break;

		case 2:// Blink the BLUE led when switch is pressed
			LedBlink(LED_BLUE_PIN,250);
			break;

		case 3:// Blink the ALL  led when switch is pressed
			LedOn(LED_ORANGE_PIN);
			LedOn(LED_RED_PIN);
			LedOn(LED_BLUE_PIN);
			DelayMs(500);
			break;

		}

       switch_prssed =(switch_prssed + 1) % 4;

      SwitchExtiFlag = 0;   // reset the flag here switch is initial

	}


	return 0;
}
